[package]
name = "dioxus-fontawesome-examples"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = "0.2"
heck = "0.4"
regex = "1.6"
scraper = "0.17"
walkdir = "2.3"
